# Generated by Django 2.0 on 2018-02-11 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('basics5e', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.IntegerField(default=10)),
                ('modifier', models.IntegerField(default=0)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='basics5e.Attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='basics5e.Class')),
            ],
        ),
        migrations.CreateModel(
            name='CombatPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_max', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField(default=0)),
                ('death_save_passes', models.IntegerField(default=0)),
                ('death_save_fails', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=10)),
                ('last_attack_name', models.CharField(max_length=80)),
                ('last_attack_damage', models.CharField(max_length=20)),
                ('hit_die_6', models.IntegerField(default=0)),
                ('hit_die_8', models.IntegerField(default=0)),
                ('hit_die_10', models.IntegerField(default=0)),
                ('hit_die_12', models.IntegerField(default=0)),
                ('spell_slot_1', models.IntegerField(default=0)),
                ('spell_slot_2', models.IntegerField(default=0)),
                ('spell_slot_3', models.IntegerField(default=0)),
                ('spell_slot_4', models.IntegerField(default=0)),
                ('spell_slot_5', models.IntegerField(default=0)),
                ('spell_slot_6', models.IntegerField(default=0)),
                ('spell_slot_7', models.IntegerField(default=0)),
                ('spell_slot_8', models.IntegerField(default=0)),
                ('spell_slot_9', models.IntegerField(default=0)),
                ('class_combat_id', models.PositiveIntegerField(null=True)),
                ('class_combat_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('alignment', models.CharField(max_length=80)),
                ('experience', models.IntegerField(default=0)),
                ('backstory', models.TextField(blank=True)),
                ('flaw', models.TextField(blank=True)),
                ('bond', models.TextField(blank=True)),
                ('strength', models.TextField(blank=True)),
                ('age', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('weight', models.CharField(max_length=20)),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basics5e.Background')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_scale', models.CharField(max_length=80)),
                ('duration_time', models.IntegerField(null=True)),
                ('effect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='basics5e.Effect')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.CombatPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('modifier', models.CharField(blank=True, max_length=80)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='basics5e.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit_points', models.IntegerField(default=0)),
                ('armor_class', models.IntegerField(default=10)),
                ('spell_dc', models.IntegerField(default=8)),
                ('movement', models.IntegerField(default=30)),
                ('base_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Class')),
                ('combat_player', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='player.CombatPlayer')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='player.Details')),
                ('feats', models.ManyToManyField(to='basics5e.Feat')),
                ('languages', models.ManyToManyField(to='basics5e.Language')),
                ('proficiencies', models.ManyToManyField(to='basics5e.Attribute')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='basics5e.Race')),
                ('spells', models.ManyToManyField(to='basics5e.Spell')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.Player'),
        ),
        migrations.AddField(
            model_name='combatplayer',
            name='equipped_offhand_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_for_offhand_weapon', to='player.Item'),
        ),
        migrations.AddField(
            model_name='combatplayer',
            name='equipped_weapon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_for_weapon', to='player.Item'),
        ),
        migrations.AddField(
            model_name='combatplayer',
            name='worn_armor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_for_armor', to='player.Item'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='player.Player'),
        ),
    ]
